# Generated by Django 3.2 on 2021-04-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='contents',
        ),
    ]
